### ISSUE TITLE
The type 'Hammock.RestResponse' exists in both 'Hammock.ClientProfile.dll'Hammock.dll'

### ISSUE THREAD

**Issue by jdschuitemaker** [danielcrenna/hammock#82]
I am new to C#, but not new to .Net. Don't know how to solve this:

Error	5	The type 'Hammock.RestResponse' exists in both 'z:\Visual Studio 2008\Projects\myApplication\packages\Hammock.1.3.1\lib\3.5\Hammock.ClientProfile.dll' and 'z:\Visual Studio 2008\Projects\myApplication\packages\Hammock.1.3.1\lib\3.5\Hammock.dll'	Z:\Visual Studio 2008\Projects\myApplication\cInternet2\TweetSharper.cs	26	17	cInternet2

I have been playing with the example to upload images from https://github.com/danielcrenna/tweetsharp/blob/master/README.md#oauth-delegation-with-echo

![2013_06_18_20_21_53_microsoft_visual_studio_administrator_](https://f.cloud.github.com/assets/2353413/670518/8bbe023a-d844-11e2-8b60-c9d75a4e27a8.png)

**Comment by depeter** [comment]
Just one of the references in your project and you'll be fine :-)
